pipelines:
  branches:
    9.x-dev:
      - step:
          name: Build and Install
          image: drud/ddev-webserver:v1.16.1
          script:
            - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
            - git fetch --unshallow
            - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
            - git fetch origin
            - git checkout 9.x
            - git merge -s ours 9.x-dev --no-commit --no-ff
            - git checkout 9.x-dev .
            - composer install
            - npm install
            - echo "// @ts-nocheck" | cat - public/typo3/sysext/backend/Resources/Private/TypeScript/Modal.ts > temp && mv temp public/typo3/sysext/backend/Resources/Private/TypeScript/Modal.ts
            - npm run build
            - chmod +x Build/Scripts/cleanUp.sh && ./Build/Scripts/cleanUp.sh
            - git add */.*
            - 'if [[ $(git status --porcelain --untracked-files=no | wc -l) -gt "0" ]]; then git commit -a -m "build: $BITBUCKET_COMMIT_SHORT" || true; fi'
            - export TYPO3_EXT_VERSION=$(cat ext_emconf.php | grep version* | grep -Po "(\d+\.)+\d+")
            - export LATEST_TAG=$(git describe --abbrev=0 --tags | grep -Po "(\d+\.)+\d+")
            - export GIT_LOG=$(git log "v$LATEST_TAG"..HEAD --pretty=format:"%s")
            - 'if [ "$TYPO3_EXT_VERSION" != "$LATEST_TAG" ]; then git tag -a "v$TYPO3_EXT_VERSION" -m "$GIT_LOG"; fi'
            - git push origin 9.x --tags
